### ISSUE TITLE
Memory leak and high GC activity

### ISSUE THREAD

**Issue by bytecode-nu** [rds1983/NuklearSharp#1]
There seems to be a (unmanaged) memory leak. To demonstrate this, open NuklearTest sample from the readme or the extended sample in the source code, and add the following to "stress test" the code:
```
graphics.SynchronizeWithVerticalRetrace = false;
IsFixedTimeStep = false;
```
Start the sample and let it run for a few minutes. After some time, the amount of memory reported by Visual Studio (in my case) have multiplied. When I did this with the NuklearTest sample, it allocated about 1 MB of memory per second.  Furthermore, GC activity was very high. 
![GC Activity](https://i.gyazo.com/8feff34f61026a8165935cb13dc5da10.png)

Some notes:
* I don't think the task manager measures memory allocated on the GPU, but Visual Studio seems to do so. 
* NuklearTest ran at around 2000 fps for me (very nice), and the issue is not as obvious when running at just 60 fps. The amount of allocated memory went from 87 MB to 313 MB after 5 minutes
* I took two memory snapshots with Visual Studio, one at the start and one after a while, to see which objects are leaking. However, I didn't find anything as it only tracks managed memory.  Thus, unmanaged memory is probably leaking. 
![Snapshots](https://i.gyazo.com/ebb03f30e8536c0660008aef23b7a7e6.png)

**Comment by rds1983** [comment]
Thanks for reporting this issue.
I plan to completely remove unmanaged memory allocation from the UI rendering(though it'll remain in functions that arent called every frame like loading ttf font).
I've already replaced nuklear nk_buffer - which used unmanaged allocation - with [NkBuffer](https://github.com/rds1983/NuklearSharp/blob/master/NuklearSharp/NkBuffer.cs), which does only managed allocation. And nk_str with [NkStr](https://github.com/rds1983/NuklearSharp/blob/master/NuklearSharp/NkStr.cs), which is simply wrapper for string.
But there are still functions where native allocation occur. Hopefully after removing it, this issue would be resolved.

**Comment by rds1983** [comment]
Btw, there is a way to exactly how much unmanaged memory had been allocated. It is stored in the static property AllocatedTotal of the Pointer class. It's usage is demonstrated in the RaizamTest.

**Comment by bytecode-nu** [comment]
I'm not sure if the sichem allocated total is correct, it seems to stay around 69k-70k regardless of how long I let NuklearTest run. If I let NuklearTest run for 30 minutes at 2000 fps, then the process memory is 722 MB (started at 89 MB). However, Windows' task manager says the process memory is 348 MB (started at 50 MB). Is GPU memory leaking? (RenderTarget, Textures, etc.) 

Snapshots taken from within Visual Studio is only for managed memory, and it reports that the total amount of allocated managed memory is not growing. It's strange that there is so much GC activity. Is the GC called explicitly somewhere? 

![VS](https://i.gyazo.com/68d41b45c4a278aef92a684f819aeba8.png)

**Comment by rds1983** [comment]
I couldn't reproduce this issue on my env(win7x64).
Do you use latest version(0.2.0.9)?

**Comment by bytecode-nu** [comment]
I used the test on the front page, which appears to be running 0.1.0.7. I tried to reproduce the problems using the latest version but I am running into another problem that is probably hiding this issue. Namely, the frame-rate drops to around 30 fps. This means that it will take about 66 times longer to render the same amount of frames, and, if the issue is still present, probably 66 times longer to leak as much memory. 

Have you tried to also print your fps? Maybe you're running into the same problem? Both the Extended and RaizamTest starts out running at a high frame-rate and then it drops to 30 fps. The GC activity is very high at the beginning and after the frame-rate drops it becomes more normal (although still high, imo). 

![Mem and CPU usage](https://i.gyazo.com/f1c7d7d883b33a123a37e315dde276c9.png)

You can probably spot when the frame-rate somehow got stuck at 30 fps :^)

**Comment by rds1983** [comment]
How do you count fps?
As my framerate keeps stable around 700.

**Comment by bytecode-nu** [comment]
I believe I tested this on the latest version before opening an issue, but the samples are behaving different now. I restarted my computer, now the fps 'only' drops to 50 fps (instead of 30 fps). I'm not sure why my fps drops. I add a simple label at some appropriate place: 

```cs
_nuklearContext.Label($"{1 / gameTime.ElapsedGameTime.TotalSeconds:F2}", Nuklear.NK_TEXT_LEFT);
```

Are you unable to reproduce it with the 0.1.0.7 version as well? Just to confirm that it is not just on my end. It might be fixed in 0.2.0.9 but I cannot test it at the moment since my fps drops. However, I also get some strange out-of-memory errors in the samples after my fps drops (there is plenty of errors left to allocate). When trying to modify the background color (using a 'slider') in RaizamTest, I got this exception: 

```
System.OutOfMemoryException
  HResult=0x8007000E
  Message=Exception of type 'System.OutOfMemoryException' was thrown.
  Source=NuklearSharp
  StackTrace:
   at NuklearSharp.Nuklear.nk_drag_behavior(UInt32& state, nk_input _in_, nk_rect drag, nk_property_variant* variant, Single inc_per_pixel) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\Nuklear.Utility.Generated.cs:line 3465
   at NuklearSharp.Nuklear.nk_property_behavior(UInt32& ws, nk_input _in_, nk_rect property, nk_rect label, nk_rect edit, nk_rect empty, Int32& state, nk_property_variant* variant, Single inc_per_pixel) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\Nuklear.Utility.Generated.cs:line 3482
   at NuklearSharp.Nuklear.nk_do_property(UInt32& ws, nk_command_buffer _out_, nk_rect property, Char* name, nk_property_variant* variant, Single inc_per_pixel, String& buffer, Int32& state, Int32& cursor, Int32& select_begin, Int32& select_end, nk_style_property style, Int32 filter, nk_input _in_, nk_user_font font, nk_text_edit text_edit, Int32 behavior) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\Nuklear.Utility.Generated.cs:line 3570
   at NuklearSharp.Nuklear.nk_property_(nk_context ctx, Char* name, nk_property_variant* variant, Single inc_per_pixel, Int32 filter) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\Nuklear.cs:line 899
   at NuklearSharp.Nuklear.nk_propertyi(nk_context ctx, Char* name, Int32 min, Int32 val, Int32 max, Int32 step, Single inc_per_pixel) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\Nuklear.Context.Generated.cs:line 3644
   at NuklearSharp.BaseContext.Propertyi(String name, Int32 min, Int32 val, Int32 max, Int32 step, Single inc_per_pixel) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\NuklearSharp\BaseContext.Generated.cs:line 1130
   at RaizamTest.GameTest.Draw(GameTime gameTime) in C:\Users\thorg\Downloads\NuklearSharp-0.2.0.9\Samples\RaizamTest\GameTest.cs:line 128
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at RaizamTest.Program.Main(String[] args) in C:\Users\<User>\Downloads\NuklearSharp-0.2.0.9\Samples\RaizamTest\Program.cs:line 9
```

I didn't get this exception a few days ago, when playing around with the samples. Confusing. I'm running Windows 10.

**Comment by rds1983** [comment]
No, sorry, I can't reproduce memory leaks with nor version on front page(0.1.0.7), nor with the latest(0.2.0.9). I've even installed GPU-Z to watch GPU memory usage and it doesnt seem to grow.
Anyway I've removed NuklearTest.zip from README.md. As latest version is supposed to be used, while that one references 0.1.0.7.
I can't reproduce also FPS dropdown with latest version(0.2.0.9)

**Comment by rds1983** [comment]
Btw, make sure both NuklearSharp references(NuklearSharp.dll and NuklearSharp.MonoGame.dll) have same version.

**Comment by bytecode-nu** [comment]
Well, sadly I'm not able to fix these issues. I've only experienced with your samples and when switching to NuklearSharp. dotMemory from JetBrains shows that it is indeed unmanaged memory that is leaking: 

![dotMemory](https://i.gyazo.com/7fd6125ef02ce6c75e27741934790e52.png)

I used dotMemory on the old version of NuklearSharp since the newer version actually crashed dotMemory itself. Well, I feel like that shouldn't happen so it might be a bug with my installation of something. I'll poke around and see what comes up. (Both dlls have the same version.)

Sorry if it turns out that it was on my end and I led you on a wild goose chase :-)

**Comment by bytecode-nu** [comment]
I was able to get the sample to not leak memory and significantly reduce GC activity by referencing another MonoGame dll. So it seems that the the problem lies elsewhere :-) I haven't gotten it to work in my game yet, but I am hopeful that I can get NuklearSharp to work properly in my project.
